-- Tear down initial schema (dev reset only).
DROP TRIGGER IF EXISTS reports_set_updated_at ON reports;
DROP TRIGGER IF EXISTS conversations_set_updated_at ON conversations;
DROP TRIGGER IF EXISTS communities_set_updated_at ON communities;
DROP TRIGGER IF EXISTS friendships_set_updated_at ON friendships;
DROP TRIGGER IF EXISTS devices_set_updated_at ON devices;
DROP TRIGGER IF EXISTS profiles_set_updated_at ON profiles;
DROP TRIGGER IF EXISTS users_set_updated_at ON users;
DROP FUNCTION IF EXISTS set_updated_at();

DROP TABLE IF EXISTS user_sanctions CASCADE;
DROP TABLE IF EXISTS moderation_actions CASCADE;
DROP TABLE IF EXISTS moderation_cases CASCADE;
DROP TABLE IF EXISTS report_subjects CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS notification_preferences CASCADE;
DROP TABLE IF EXISTS story_views CASCADE;
DROP TABLE IF EXISTS story_items CASCADE;
DROP TABLE IF EXISTS stories CASCADE;
DROP TABLE IF EXISTS message_media CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS conversation_participants CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS media_variants CASCADE;
DROP TABLE IF EXISTS media CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS community_members CASCADE;
DROP TABLE IF EXISTS communities CASCADE;
DROP TABLE IF EXISTS friendships CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS public_aliases CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS sanction_type;
DROP TYPE IF EXISTS moderation_action_type;
DROP TYPE IF EXISTS moderation_case_status;
DROP TYPE IF EXISTS report_subject_type;
DROP TYPE IF EXISTS report_status;
DROP TYPE IF EXISTS notification_channel;
DROP TYPE IF EXISTS media_variant_type;
DROP TYPE IF EXISTS media_status;
DROP TYPE IF EXISTS message_type;
DROP TYPE IF EXISTS conversation_type;
DROP TYPE IF EXISTS community_member_role;
DROP TYPE IF EXISTS community_visibility;
DROP TYPE IF EXISTS friendship_status;
DROP TYPE IF EXISTS device_platform;
DROP TYPE IF EXISTS user_status;
